### ISSUE TITLE
Extra "y" in "Batteryy" status header

### ISSUE THREAD

**Issue by johnbentcope** [rM-self-serve/neofetch-rM#1]
It appears like there's a typo in the spelling of "Battery" on the output in the RM2.

![IMG_20240302_085959456_MP.jpg](https://github.com/rM-self-serve/neofetch-rM/assets/329833/60a9cece-c4f3-4bd5-b6fa-956c14bd58fb)

**Comment by rM-self-serve** [comment]
Can you share the device name found when running `ls /sys/class/power_supply/`? Does it end in 'y'?

**Comment by rM-self-serve** [comment]
In any case, this should fix the issue. Thanks for reporting!

Its just a shell script so you can wget https://raw.githubusercontent.com/rM-self-serve/neofetch-rM/bugfix/neofetch

**Comment by johnbentcope** [comment]
It does!

ls /sys/class/power_supply
max77818-charger max77818_battery
